# file: /Users/aliciayrvn/Downloads/data-center-dispatch/backend/app/routers/auth.py
# hypothesis_version: 6.135.1

[401, '/auth', '/auth/login', '/login', '1234', 'HS256', 'Invalid token', 'Not authorized', 'access_token', 'admin', 'auth', 'bearer', 'exp', 'sub', 'supersecret', 'token_type']